//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWER
    {
        public decimal ID { get; set; }
        public string PERSONCODE { get; set; }
        public string PERSONNAME { get; set; }
        public string USERCODE { get; set; }
        public string SCORE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
    }
}
