//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWERLINE
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ANSWERID { get; set; }
        public string QUESTION { get; set; }
        public string ANSWER { get; set; }
    }
}
